min_ndet: 1 # Default:2
min_tspan: -1  # Default 0, but that rejects everything!
max_tspan: 365
min_rb: 0.3
max_fwhm: 5.5
max_elong: 1.4
max_magdiff: 1.0
max_nbad: 2
min_sso_dist: 20
min_gal_lat: 0.0  # Default: 14
gaia_rs: 10.0
gaia_pm_signif: 3
gaia_plx_signif: 3
gaia_veto_gmag_min: 9
gaia_veto_gmag_max: 20
gaia_excessnoise_sig_max: 999
ps1_sgveto_rad: 1.0
ps1_sgveto_th: 0.8
ps1_confusion_rad: 3.0
ps1_confusion_sg_tol: 0.1